### ISSUE TITLE
Submission deadline for Wikimania is approaching

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ContentMine/wikifactmine-api#15]
Originally March 30, now April 10:
https://wikimania2017.wikimedia.org/wiki/Submissions

**Comment by tarrow** [comment]
Thanks @Daniel-Mietchen. I had noticed this and must confess that I de-prioritised the submission slightly thanks to the extended deadline.

I think we're going to put in for the standard 25mins talk. Probably going to presented by me and the WiR. Does that sound good to you?

I was wondering if perhaps we should go for a workshop instead though.

Do you have any thoughts?

**Comment by Daniel-Mietchen** [comment]
Sounds good. I like the idea of going for a workshop in principle, but then, technical issues have to be sorted out beforehand (see my notes at https://github.com/ContentMine/FutureTDM/issues ), otherwise, they will limit the usefulness of such a 55-min session.

We should also think about what to do at the hackathon and at WikiCite. I am still interested in a ContentMine-based pipeline for P921 of instances of scientific articles, as per
- https://github.com/ContentMine/old_site/issues/232#issuecomment-204011068
- https://github.com/ContentMine/getpapers/issues/126
- https://github.com/sparcopen/open-research-doathon/issues/51

**Comment by tarrow** [comment]
Totally blank submission made here.

I'll be trickling in content over the week.

https://wikimania2017.wikimedia.org/wiki/Submissions/WikiFactMine_-_Enhancing_Wikidata_by_Mining_the_Scientific_Literature
