### ISSUE TITLE
2item end point returns non-co-occuring items

### ISSUE THREAD

**Issue by tarrow** [ContentMine/wikifactmine-api#17]
Discovered by @Daniel-Mietchen.

Example is http://tools.wmflabs.org/wikifactmine-api/api/2item/Q202864/Q125928

Which returns facts from PMC5176245 even thought it doesn't address the two items

**Comment by Daniel-Mietchen** [comment]
Here's the set of papers that would be expected as result: https://www.ncbi.nlm.nih.gov/pmc/?term=(%22zika+virus%22+OR+zikv)+AND+%22climate+change%22 .
